//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APERTURE_LIBRARY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public Clientes()
        {
            this.Prestamos = new HashSet<Prestamos>();
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int IdCLI { get; set; }
        public string NombreCli { get; set; }
        public string ApePat { get; set; }
        public string ApeMat { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string correo { get; set; }
        public Nullable<int> NumTelefono { get; set; }
        public string Domicilio { get; set; }
    
        public virtual ICollection<Prestamos> Prestamos { get; set; }
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
