//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APERTURE_LIBRARY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Prestamos = new HashSet<Prestamo>();
            this.Ventas = new HashSet<Venta>();
        }
    
        public int IdCLI { get; set; }
        public string NombreCli { get; set; }
        public string ApePat { get; set; }
        public string ApeMat { get; set; }
        public string FechaNacimiento { get; set; }
        public string correo { get; set; }
        public Nullable<int> NumTelefono { get; set; }
        public string Domicilio { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<Prestamo> Prestamos { get; set; }
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
