//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APERTURE_LIBRARY.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryAPEntities : DbContext
    {
        public LibraryAPEntities()
            : base("name=LibraryAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Checadas> Checadas { get; set; }
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<Libros> Libros { get; set; }
        public DbSet<Personal> Personal { get; set; }
        public DbSet<Prestamos> Prestamos { get; set; }
        public DbSet<TipoLibros> TipoLibros { get; set; }
        public DbSet<TiposPrestamos> TiposPrestamos { get; set; }
        public DbSet<Ventas> Ventas { get; set; }
        public DbSet<VentasLibro> VentasLibro { get; set; }
    }
}
