//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APERTURE_LIBRARY.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryAPEntities : DbContext
    {
        public LibraryAPEntities()
            : base("name=LibraryAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Checada> Checadas { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<Libro> Libros { get; set; }
        public DbSet<Personal> Personals { get; set; }
        public DbSet<Prestamo> Prestamos { get; set; }
        public DbSet<TipoLibro> TipoLibros { get; set; }
        public DbSet<TiposPrestamo> TiposPrestamos { get; set; }
        public DbSet<Venta> Ventas { get; set; }
        public DbSet<VentasLibro> VentasLibros { get; set; }
    }
}
