//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APERTURE_LIBRARY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public Libros()
        {
            this.Prestamos = new HashSet<Prestamos>();
            this.VentasLibro = new HashSet<VentasLibro>();
        }
    
        public int IdLibro { get; set; }
        public string NombreLibro { get; set; }
        public string Autor { get; set; }
        public string Editorial { get; set; }
        public string FPublicacion { get; set; }
        public Nullable<double> CostoLibros { get; set; }
        public Nullable<int> CantidadLibros { get; set; }
        public Nullable<int> NoPaginas { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> idtipolibro { get; set; }
    
        public virtual ICollection<Prestamos> Prestamos { get; set; }
        public virtual ICollection<VentasLibro> VentasLibro { get; set; }
        public virtual TipoLibros TipoLibros { get; set; }
    }
}
