//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APERTURE_LIBRARY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public Libros()
        {
            this.Prestamos = new HashSet<Prestamos>();
            this.VentasLibros = new HashSet<VentasLibros>();
        }
    
        public int IdLibro { get; set; }
        public string NombreLibro { get; set; }
        public string Autor { get; set; }
        public string Editorial { get; set; }
        public string FPublicacion { get; set; }
        public Nullable<double> CostoLibros { get; set; }
        public Nullable<int> CantidadLibros { get; set; }
        public Nullable<int> NoPaginas { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> idtipolibro { get; set; }
    
        public virtual ICollection<Prestamos> Prestamos { get; set; }
        public virtual ICollection<VentasLibros> VentasLibros { get; set; }
        public virtual TipoLibros TipoLibros { get; set; }
    }
}
