//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APERTURE_LIBRARY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public Personal()
        {
            this.Checadas = new HashSet<Checadas>();
            this.Prestamos = new HashSet<Prestamos>();
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int IdPE { get; set; }
        public Nullable<int> IdPersonal { get; set; }
        public string NombrePer { get; set; }
        public string ApePat { get; set; }
        public string ApeMat { get; set; }
        public string FechaNacimiento { get; set; }
        public string correo { get; set; }
        public string NumTelefono { get; set; }
        public string Domicilio { get; set; }
        public string Puesto { get; set; }
        public string Turno { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<Checadas> Checadas { get; set; }
        public virtual ICollection<Prestamos> Prestamos { get; set; }
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
