//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APERTURE_LIBRARY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public int IdPR { get; set; }
        public Nullable<System.DateTime> FechaPrestamoInicial { get; set; }
        public Nullable<System.DateTime> FechaPrestamoFinal { get; set; }
        public Nullable<double> CostoPrestamo { get; set; }
        public string DescripcionLibro { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idPersonal { get; set; }
        public Nullable<int> idlibro { get; set; }
        public Nullable<int> idtipoprestamo { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Libros Libros { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual TiposPrestamos TiposPrestamos { get; set; }
    }
}
