//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APERTURE_LIBRARY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int IdRE { get; set; }
        public Nullable<double> VentasTotalDelDia { get; set; }
        public Nullable<double> PrestamosTotalDelDia { get; set; }
        public string FechaDia { get; set; }
        public Nullable<int> idPersonal { get; set; }
    
        public virtual Personal Personal { get; set; }
    }
}
