//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APERTURE_LIBRARY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoLibros
    {
        public TipoLibros()
        {
            this.Libros = new HashSet<Libros>();
        }
    
        public int IdTL { get; set; }
        public string Genero { get; set; }
        public string Categoria { get; set; }
    
        public virtual ICollection<Libros> Libros { get; set; }
    }
}
