//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APERTURE_LIBRARY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoLibros
    {
        public TipoLibros()
        {
            this.Libros = new HashSet<Libros>();
        }
    
        public int IdTL { get; set; }
        public string Genero { get; set; }
        public string Categoria { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<Libros> Libros { get; set; }
    }
}
