//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APERTURE_LIBRARY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasLibros
    {
        public int IdVELIB { get; set; }
        public Nullable<int> idLibro { get; set; }
        public Nullable<int> idVentas { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Libros Libros { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
